### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by Vujas-Eteph** [Vujas-Eteph/GPUNotif#1]
TO-DO:
- [ ] Connect the GPU Notificator with the GPU Watcher
- [ ] Make a README.md
- [ ] Make a requirement.txt
